;;; any.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'any
    :syntax :proto3

     :package "google.protobuf")
)


;;; Top-Level messages

(pi:define-message any
    ()
  ;; Fields
  (type-url
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeUrl")
  (value
   :index 2 :type cl-protobufs:byte-vector :kind :scalar :label (:optional) :json-name "value"))

(cl:export '(any
             type-url
             value))
