;;; timestamp.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'timestamp
    :syntax :proto3

     :package "google.protobuf")
)


;;; Top-Level messages

(pi:define-message timestamp
    ()
  ;; Fields
  (seconds
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "seconds")
  (nanos
   :index 2 :type cl-protobufs:int32 :kind :scalar :label (:optional) :json-name "nanos"))


(cl:export '(nanos
             seconds
             timestamp))
