;;; meshtastic/mqtt.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.MESHTASTIC")
    (cl:defpackage "CL-PROTOBUFS.MESHTASTIC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.MESHTASTIC")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'mqtt
    :syntax :proto3

     :package "meshtastic"
))


;;; Top-Level messages

(pi:define-message service-envelope
    ()
  ;; Fields
  (packet
   :index 1 :type cl-protobufs.meshtastic::mesh-packet :kind :message :label (:optional) :json-name "packet")
  (channel-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "channelId")
  (gateway-id
   :index 3 :type cl:string :kind :scalar :label (:optional) :json-name "gatewayId"))

(cl:export '(channel-id
             gateway-id
             mqtt
             packet
             service-envelope))
