;;; meshtastic/portnums.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.MESHTASTIC")
    (cl:defpackage "CL-PROTOBUFS.MESHTASTIC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.MESHTASTIC")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'portnums
    :syntax :proto3

     :package "meshtastic")
)


;;; Top-Level enums

(pi:define-enum port-num
    ()
  (:unknown-app :index 0)
  (:text-message-app :index 1)
  (:remote-hardware-app :index 2)
  (:position-app :index 3)
  (:nodeinfo-app :index 4)
  (:routing-app :index 5)
  (:admin-app :index 6)
  (:text-message-compressed-app :index 7)
  (:waypoint-app :index 8)
  (:audio-app :index 9)
  (:reply-app :index 32)
  (:ip-tunnel-app :index 33)
  (:serial-app :index 64)
  (:store-forward-app :index 65)
  (:range-test-app :index 66)
  (:telemetry-app :index 67)
  (:zps-app :index 68)
  (:simulator-app :index 69)
  (:traceroute-app :index 70)
  (:neighborinfo-app :index 71)
  (:private-app :index 256)
  (:atak-forwarder :index 257)
  (:max :index 511))

(cl:export '(port-num
             port-num-int-to-keyword
             port-num-keyword-to-int
             portnums))
