;;; meshtastic/rtttl.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.MESHTASTIC")
    (cl:defpackage "CL-PROTOBUFS.MESHTASTIC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.MESHTASTIC")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'rtttl
    :syntax :proto3

     :package "meshtastic")
)


;;; Top-Level messages

(pi:define-message rtttl-config
    (
     :name "RTTTLConfig")
  ;; Fields
  (ringtone
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "ringtone"))

(cl:export '(ringtone
             rtttl
             rtttl-config))
