;;; needed for cross-compiling
;;; (ECL functions defined directly in C++)

(in-package :qml)

(defun clipboard-text ())
(defun %disable-clipboard-menu (a))
(defun %ensure-permissions (a))
(defun %js (a b))
(defun pixel-ratio ())
(defun %qapropos (a b c))
(defun qchildren (a))
(defun qcopy-file (a b))
(defun qdirectory (a))
(defun qescape (a))
(defun %qexec (a))
(defun qexit ())
(defun qfind-child (a b))
(defun %qfind-children (a b c))
(defun qfrom-utf8 (a))
(defun qinvoke-method (a b c d))
(defun %qload-c++ (a b))
(defun %qlog (a))
(defun qnull (a))
(defun %qml-get (a b))
(defun %qml-set (a b c))
(defun qobject-name (a))
(defun %qprocess-events (a))
(defun %qquit (a))
(defun %qrun-on-ui-thread (a b))
(defun %qget (a b))
(defun %qset (a b))
(defun %qsingle-shot (a b))
(defun qtranslate (a b c))
(defun qversion ())
(defun qt-object-info (a))
(defun %reload ())
(defun root-item ())
(defun set-clipboard-text (a))
(defun %set-shutdown-p (a))
